import * as THREE from 'three';
import { VoxelBatch, disposeGroup, randomFor } from './VoxelBatch.js';
import { isGameplayClearance } from './GameplayLayout.js';
import { defineWorldDomain } from '../engine/DomainInterface.js';
import { GDO_WATER_SURFACE_SOURCE, classifyWaterContact } from '../engine/WaterContact.js';

export const WORLD = Object.freeze({ min: -128, max: 128, chunkSize: 32, tileSize: 4, waterY: 0 });
export const GDO_CURATED_DOMAIN_ID = 'curated';
/** `FND-08`: the curated island declares the same interface as the coordinate
 * world at its own scale — one world unit per metre, a fixed 256 × 256 island,
 * graded bridge/vault structures, and no coordinate or streamed capability. */
export const GDO_CURATED_WORLD_DOMAIN = defineWorldDomain({
  id: GDO_CURATED_DOMAIN_ID,
  label: 'Curated island',
  unitsPerMetre: 1,
  bounds: { minX: WORLD.min, maxX: WORLD.max, minZ: WORLD.min, maxZ: WORLD.max },
  capabilities: { terrainSupport: true, verticalGrades: true },
});
export const LANDMARKS = Object.freeze({ gateway: [-66, -44], chariot: [62, -44] });

function cameraBox(x, y, z, sizeX, sizeY, sizeZ, id) {
  const halfX = sizeX / 2, halfY = sizeY / 2, halfZ = sizeZ / 2;
  const box = new THREE.Box3(
    new THREE.Vector3(x - halfX, y - halfY, z - halfZ),
    new THREE.Vector3(x + halfX, y + halfY, z + halfZ),
  );
  box.userData = { id, role: 'camera-blocker' };
  return box;
}

/** Tight landmark compounds preserve the Gateway arch instead of one enclosing AABB. */
export function createLandmarkCameraBlockers() {
  const boxes = [];
  const [gatewayX, gatewayZ] = LANDMARKS.gateway;
  boxes.push(cameraBox(gatewayX, 3.5, gatewayZ, 29, 1, 15, 'gateway:plinth'));
  for (const side of [-1, 1]) {
    boxes.push(cameraBox(gatewayX + side * 9, 12, gatewayZ, 9, 18, 9, `gateway:pier:${side}`));
    for (let step = 0; step < 5; step++) {
      boxes.push(cameraBox(
        gatewayX + side * (4.3 - step * .65),
        14 + step * 1.1,
        gatewayZ,
        1.4,
        1.3,
        9,
        `gateway:arch:${side}:${step}`,
      ));
    }
  }
  boxes.push(cameraBox(gatewayX, 21.25, gatewayZ, 30, 4.5, 12, 'gateway:lintel'));
  for (const dx of [-11, 11]) for (const dz of [-4, 4]) {
    boxes.push(cameraBox(gatewayX + dx, 28, gatewayZ + dz, 4, 10, 4, `gateway:tower:${dx}:${dz}`));
  }

  const [chariotX, chariotZ] = LANDMARKS.chariot;
  boxes.push(cameraBox(chariotX, 4, chariotZ, 23, 2, 21, 'chariot:plinth'));
  boxes.push(cameraBox(chariotX, 7, chariotZ, 14, 4, 12, 'chariot:body'));
  for (const dx of [-5, 5]) for (const dz of [-5, 5]) {
    boxes.push(cameraBox(chariotX + dx, 7, chariotZ + dz * 1.3, 7, 7, 1.8, `chariot:wheel:${dx}:${dz}`));
    boxes.push(cameraBox(chariotX + dx, 14, chariotZ + dz * .7, 1.8, 10, 1.8, `chariot:column:${dx}:${dz}`));
  }
  for (let tier = 0; tier < 6; tier++) {
    boxes.push(cameraBox(
      chariotX,
      19 + tier * 1.3,
      chariotZ,
      17 - tier * 2,
      1.3,
      14 - tier * 1.7,
      `chariot:roof:${tier}`,
    ));
  }
  return boxes;
}

/** Deterministic proxies for solid skyline/rail masses generated by streamed chunks. */
export function createOrdinaryStructureCameraBlockers(seed = 2026, decorationDensity = 1) {
  const boxes = [];
  for (let x = WORLD.min + 2; x < WORLD.max; x += WORLD.tileSize) {
    for (let z = WORLD.min + 2; z < WORLD.max; z += WORLD.tileSize) {
      const height = terrainHeight(x, z);
      if (height < 0) continue;
      const landmarkReserved = Object.values(LANDMARKS).some(([lx, lz]) => Math.abs(x - lx) < 19 && Math.abs(z - lz) < 18);
      if (landmarkReserved || isGameplayClearance(x, z) || (biomeAt(x, z) === 'maharashtra' && Math.abs(z + 80) < 7)) continue;
      const structure = ordinaryStructureAt(x, z, biomeAt(x, z), height, randomFor(x, z, seed), decorationDensity);
      if (!structure) continue;
      const box = cameraBox(
        x,
        height + structure.height / 2,
        z,
        structure.size,
        structure.height,
        structure.size,
        `${structure.kind}:${x}:${z}`,
      );
      boxes.push(box);
    }
  }

  // The generated elevated railway is one continuous deck plus tight piers.
  boxes.push(cameraBox(-64, 5.175, -80, 128, 1.85, 7, 'railway:deck'));
  for (let x = WORLD.min + 4; x < 0; x += 8) {
    boxes.push(cameraBox(x, 1.5, -80, 2, 7, 5, `railway:pier:${x}`));
  }
  return boxes;
}

export function biomeAt(x, z) { return z >= 12 ? 'kerala' : x < 0 ? 'maharashtra' : 'karnataka'; }
export function riverX(z) { return 9 * Math.sin(z / 28) + 4 * Math.cos(z / 17); }

/** Shared deterministic land/water contract: generator, decoration, and caller queries. */
export function terrainHeight(x, z) {
  if (x < WORLD.min || x >= WORLD.max || z < WORLD.min || z >= WORLD.max) return -3;
  const mainRiver = Math.abs(x - riverX(z)) < (z > 12 ? 15 : 10);
  const backwater = z > 20 && Math.abs(z - (55 + 9 * Math.sin(x / 24))) < 11;
  if (mainRiver || backwater) return -3;
  if (z < 12) return 3;
  const hill = Math.max(0, 1 - Math.hypot((x - 82) / 56, (z - 92) / 53));
  return 3 + Math.floor(hill * 8) * 2;
}

function ordinaryStructureAt(x, z, biome, height, random, decorationDensity) {
  if (biome === 'karnataka' && x > 40 && z < -80 && x % 12 === 2 && z % 12 === -10 &&
      (decorationDensity >= 1 || random() < decorationDensity)) {
    return { kind: 'tech-tower', height: 15 + random() * 28, size: 6, color: '#287bb8', opacity: .65 };
  }
  if (biome === 'maharashtra' && z < -90 && random() < .16 * decorationDensity) {
    return { kind: 'skyline-tower', height: 10 + random() * 22, size: 3.4, color: '#d0c8b6', opacity: 1 };
  }
  return null;
}

function palm(batch, x, y, z, random) {
  const h = 7 + random() * 4;
  for (let i = 0; i < 5; i++) batch.box(x + i * .15, y + (i + .5) * h / 5, z, .65, h / 5, .65, '#86603a');
  for (let i = 0; i < 7; i++) {
    const a = i * Math.PI * 2 / 7;
    for (let j = 1; j <= 3; j++) batch.box(x + Math.cos(a) * j * 1.1, y + h - j * .5, z + Math.sin(a) * j * 1.1,
      2.2, .4, 1.1, i % 2 ? '#4f882b' : '#659e32', [0, -a, 0]);
  }
}

function gateway(batch, x, z) {
  const stone = '#c6a06b', trim = '#e4c28a', y = 3;
  batch.box(x, y + .5, z, 29, 1, 15, trim);
  // Real opening: two piers and stepped arch voussoirs, never a painted doorway.
  for (const side of [-1, 1]) {
    batch.box(x + side * 9, y + 9, z, 9, 18, 9, stone);
    for (let step = 0; step < 5; step++) batch.box(x + side * (4.3 - step * .65), y + 11 + step * 1.1, z, 1.4, 1.3, 9, trim);
  }
  batch.box(x, y + 18, z, 29, 3, 11, stone);
  for (const level of [17, 20]) batch.box(x, y + level, z, 30, .7, 12, trim);
  for (const dx of [-11, 11]) for (const dz of [-4, 4]) {
    batch.box(x + dx, y + 23, z + dz, 3, 6, 3, trim);
    for (let i = 0; i < 3; i++) batch.box(x + dx, y + 26 + i * .6, z + dz, 4 - i, .7, 4 - i, stone);
    batch.box(x + dx, y + 29, z + dz, .5, 2, .5, '#80623b');
  }
  for (let i = -13; i <= 13; i += 2) batch.box(x + i, y + 21, z + 5, .7, 1.5, 1, stone);
}

function chariot(batch, x, z) {
  const stone = '#c9a777', dark = '#997d59';
  batch.box(x, 4, z, 23, 2, 21, stone);
  batch.box(x, 7, z, 14, 4, 12, dark);
  for (const dx of [-5, 5]) for (const dz of [-5, 5]) {
    // Radial blocks form the stone wheels with carved spokes.
    for (let i = 0; i < 16; i++) {
      const a = i * Math.PI / 8;
      batch.box(x + dx + Math.sin(a) * 3, 7 + Math.cos(a) * 3, z + dz * 1.3, 1.3, 1.4, 1.3, stone, [0, 0, -a]);
    }
    for (let i = 0; i < 8; i++) batch.box(x + dx, 7, z + dz * 1.3, .45, 5, .5, stone, [0, 0, i * Math.PI / 4]);
    batch.box(x + dx, 14, z + dz * .7, 1.8, 10, 1.8, stone);
  }
  for (let i = 0; i < 6; i++) batch.box(x, 19 + i * 1.3, z, 17 - i * 2, 1.3, 14 - i * 1.7, i % 2 ? dark : stone);
}

function train() {
  const batch = new VoxelBatch();
  for (let car = 0; car < 4; car++) {
    const x = -car * 12;
    batch.box(x, 1.8, 0, 11, 3.2, 4, '#e5e4df');
    batch.box(x, 1, 0, 11.1, .65, 4.1, '#863885');
    batch.box(x, 3.5, 0, 11.3, .45, 4.3, '#bac4cb');
    for (let i = -4; i <= 4; i += 2) for (const side of [-1, 1]) batch.box(x + i, 2.5, side * 2.05, 1.1, 1.1, .1, '#213d50');
    for (const dx of [-3.5, 3.5]) batch.box(x + dx, 0, 0, 1.5, 1.1, 3.5, '#30373c');
  }
  batch.box(5.55, 1.7, 0, .2, 2.5, 4, '#edbd31');
  return batch.build();
}

function houseboat() {
  const batch = new VoxelBatch();
  batch.box(0, .5, 0, 19, 1.5, 7, '#3b2b20');
  batch.box(0, 1.5, 0, 21, .6, 7.6, '#ac7a39');
  for (const side of [-1, 1]) {
    batch.box(side * 10, 1, 0, 3, 1.2, 5, '#493226', [0, 0, side * .25]);
    for (let i = -7; i <= 7; i += 2) batch.box(i, 3, side * 3, .3, 3, .3, '#b78b4f');
    batch.box(0, 2.5, side * 3, 18, .3, .3, '#c89d62');
  }
  // Segmented barrel roof leaves the veranda and window openings visible.
  for (let i = -4; i <= 4; i++) {
    const a = i * Math.PI / 12;
    batch.box(-1, 4 + Math.cos(a) * 2, Math.sin(a) * 3.5, 15, .6, 1.2, i % 2 ? '#d3a558' : '#ba8941', [-a, 0, 0]);
  }
  batch.box(-1, 3, 0, 12, 3, 3.2, '#865c30');
  for (let i = -5; i <= 3; i += 3) for (const side of [-1, 1]) batch.box(i, 3.4, side * 1.65, 1.5, 1.5, .1, '#263933');
  return batch.build();
}

/** Streaming is deterministic, cancellable, distance-prioritized, and frame-budgeted.
 * update focus is the PLAYER/GROUND TARGET, not the elevated camera position.
 * elapsedSeconds should come from the server-synchronized world clock in multiplayer.
 */
export class BiomeManager {
  constructor(scene, { seed = 2026, loadRadius = 150, unloadRadius = 190, budgetMs = 3, decorationDensity = 1 } = {}) {
    if (!(loadRadius >= 0 && unloadRadius > loadRadius && budgetMs > 0)) throw new RangeError('Invalid streaming configuration');
    if (!(decorationDensity >= 0 && decorationDensity <= 1)) throw new RangeError('decorationDensity must be between 0 and 1');
    this.scene = scene; this.seed = seed; this.loadRadius = loadRadius;
    this.unloadRadius = unloadRadius; this.budgetMs = budgetMs; this.decorationDensity = decorationDensity;
    this.chunks = new Map(); this.disposed = false; this.actors = new Map();
    this.domain = GDO_CURATED_WORLD_DOMAIN;
    this.unitsPerMetreScale = this.domain.unitsPerMetre;
    this.domainBounds = this.domain.bounds;
    this.bounds = this.domain.bounds;
    this.cameraBlockers = [
      ...createLandmarkCameraBlockers(),
      ...createOrdinaryStructureCameraBlockers(seed, decorationDensity),
    ];
    this.descriptors = []; this.descriptorByKey = new Map();
    this._nearbyCacheKey = null; this._nearbyCache = [];
    for (let z = WORLD.min; z < WORLD.max; z += WORLD.chunkSize) {
      for (let x = WORLD.min; x < WORLD.max; x += WORLD.chunkSize) {
        const cx = x / WORLD.chunkSize, cz = z / WORLD.chunkSize;
        const descriptor = { key: `${cx}:${cz}`, cx, cz, x, z };
        this.descriptors.push(descriptor); this.descriptorByKey.set(descriptor.key, descriptor);
      }
    }
  }
  *generate(descriptor) {
    const batch = new VoxelBatch();
    const { x: ox, z: oz } = descriptor;
    for (let x = ox + 2; x < ox + 32; x += 4) {
      for (let z = oz + 2; z < oz + 32; z += 4) {
        const height = terrainHeight(x, z);
        if (height < 0) continue;
        const biome = biomeAt(x, z), random = randomFor(x, z, this.seed);
        const color = biome === 'maharashtra' ? '#b6af8f' : biome === 'karnataka' ? '#c4aa7b' : '#588d35';
        batch.box(x, (height - 3) / 2, z, 4, height + 3, 4, color);
        const landmarkReserved = Object.values(LANDMARKS).some(([lx, lz]) => Math.abs(x - lx) < 19 && Math.abs(z - lz) < 18);
        if (landmarkReserved || isGameplayClearance(x, z) || (biome === 'maharashtra' && Math.abs(z + 80) < 7)) continue;
        const structure = ordinaryStructureAt(x, z, biome, height, random, this.decorationDensity);
        if (biome === 'kerala') {
          if (height > 3) batch.box(x, height + .35, z, 3.5, .7, 2.5, '#93b93e');
          else if (random() < .18 * this.decorationDensity) palm(batch, x, height, z, random);
        } else if (structure?.kind === 'tech-tower') {
          batch.box(x, height + structure.height / 2, z, structure.size, structure.height, structure.size,
            structure.color, [0, 0, 0], structure.opacity);
          for (let y = 3; y < structure.height; y += 3) batch.box(x, height + y, z, 6.1, .2, 6.1, '#a3dbeb');
        } else if (structure?.kind === 'skyline-tower') {
          batch.box(x, height + structure.height / 2, z, structure.size, structure.height, structure.size, structure.color);
        } else if (random() < .11 * this.decorationDensity) {
          batch.box(x, height + 1.5, z, .6, 3, .6, '#785233');
          batch.box(x, height + 4, z, 3.5, 3, 3.5, '#64873c');
        }
        if (biome === 'maharashtra' && terrainHeight(x + 4, z) < 0 &&
            (this.decorationDensity >= 1 || random() < this.decorationDensity)) {
          for (const angle of [0, 2.1, 4.2]) batch.box(x + 1, 1.5, z, 1.4, 5, 1.4, '#8b9290', [.8, angle, .5]);
        }
      }
      yield; // Check the frame deadline after each eight-tile strip.
    }
    const owns = (x, z) => x >= ox && x < ox + 32 && z >= oz && z < oz + 32;
    if (owns(...LANDMARKS.gateway)) gateway(batch, ...LANDMARKS.gateway);
    if (owns(...LANDMARKS.chariot)) chariot(batch, ...LANDMARKS.chariot);
    if (oz <= -80 && oz + 32 > -80 && ox < 0) {
      batch.box(ox + 16, 5, -80, 32, 1.5, 7, '#999d93');
      for (const dz of [-1.5, 1.5]) batch.box(ox + 16, 6, -80 + dz, 32, .2, .2, '#454e54');
      for (let x = ox + 4; x < ox + 32; x += 8) batch.box(x, 1.5, -80, 2, 7, 5, '#90988d');
    }
    yield;
    return batch.build();
  }
  /** Shared support query: the island's analytic terrain height at any x/z. */
  querySupport(x, z, out = {}) {
    const y = terrainHeight(x, z);
    out.x = x; out.z = z; out.y = y;
    out.kind = y < WORLD.waterY ? 'water' : 'ground';
    out.slopeRadians = 0;
    return out;
  }
  /**
   * `COL-08`: the curated island answers the same water sensor as the coordinate
   * world — a fixed water plane at `WORLD.waterY`, the analytic terrain under it,
   * and the shared state machine. Both modes therefore share one set of rules.
   */
  waterContact(x, z, { feetY = 0, groundY = null, bodyHeight = 1.7, gravity = 30, profile = 'low' } = {},
    out = {}) {
    if (![x, z, feetY, bodyHeight, gravity].every(Number.isFinite)) {
      throw new TypeError('Curated water contact needs finite coordinates, height, and gravity');
    }
    // Bridge decks are support, so a body standing on one is above the plane.
    const ground = Number.isFinite(groundY) ? groundY
      : Math.max(terrainHeight(x, z), this.bridges?.heightAt?.(x, z) ?? -Infinity);
    const inWater = Math.abs(x) <= 126 && Math.abs(z) <= 126 && WORLD.waterY > ground;
    return classifyWaterContact({
      waterSurfaceY: WORLD.waterY, feetY, groundY: ground, bodyHeight, gravity, profile,
      inWater, wet: inWater,
      source: inWater ? GDO_WATER_SURFACE_SOURCE.CURATED_PLANE : GDO_WATER_SURFACE_SOURCE.NONE,
    }, out);
  }
  /** Shared diagnostic record: bounded numbers only, never live objects. */
  querySnapshot() {
    return {
      domain: this.domain.id,
      chunks: this.chunks.size,
      loading: this.loadingCount,
      actors: this.actors.size,
      decorations: this.decorationDensity,
      seed: this.seed,
    };
  }
  distance(descriptor, focus) {
    // Distance to chunk AABB, so boundary cells don't pop prematurely.
    const size = WORLD.chunkSize;
    const dx = Math.max(descriptor.x - focus.x, 0, focus.x - descriptor.x - size);
    const dz = Math.max(descriptor.z - focus.z, 0, focus.z - descriptor.z - size);
    return Math.hypot(dx, dz);
  }
  nearbyDescriptors(focus) {
    // Rebuild only after moving half a chunk. Work depends on the active radius,
    // not on the number of chunks in the complete world manifest.
    const size = WORLD.chunkSize;
    const cacheKey = `${Math.floor(focus.x / (size / 2))}:${Math.floor(focus.z / (size / 2))}:${this.loadRadius}`;
    if (cacheKey === this._nearbyCacheKey) return this._nearbyCache;

    const minCx = Math.max(WORLD.min / size, Math.floor((focus.x - this.loadRadius) / size) - 1);
    const maxCx = Math.min(WORLD.max / size - 1, Math.floor((focus.x + this.loadRadius) / size) + 1);
    const minCz = Math.max(WORLD.min / size, Math.floor((focus.z - this.loadRadius) / size) - 1);
    const maxCz = Math.min(WORLD.max / size - 1, Math.floor((focus.z + this.loadRadius) / size) + 1);
    const nearby = [];
    for (let cz = minCz; cz <= maxCz; cz++) for (let cx = minCx; cx <= maxCx; cx++) {
      const descriptor = this.descriptorByKey.get(`${cx}:${cz}`);
      if (!descriptor) continue;
      const distance = this.distance(descriptor, focus);
      if (distance <= this.loadRadius) nearby.push({ descriptor, distance });
    }
    nearby.sort((a, b) => a.distance - b.distance);
    this._nearbyCacheKey = cacheKey;
    this._nearbyCache = nearby.map(entry => entry.descriptor);
    return this._nearbyCache;
  }
  update(focus, elapsedSeconds) {
    if (this.disposed) return;
    if (![focus.x, focus.z, elapsedSeconds].every(Number.isFinite)) throw new TypeError('Finite focus and time required');
    for (const [key, chunk] of this.chunks) {
      if (this.distance(chunk.descriptor, focus) > this.unloadRadius) {
        if (chunk.root) disposeGroup(chunk.root);
        chunk.job?.return(); this.chunks.delete(key);
      }
    }
    const nearby = this.nearbyDescriptors(focus);
    const deadline = performance.now() + this.budgetMs;
    for (const descriptor of nearby) {
      let chunk = this.chunks.get(descriptor.key);
      if (!chunk) {
        chunk = { descriptor, root: null, job: this.generate(descriptor) };
        this.chunks.set(descriptor.key, chunk);
      }
      while (chunk.job && performance.now() < deadline) {
        const result = chunk.job.next();
        if (result.done) {
          chunk.root = result.value; chunk.root.name = `chunk:${descriptor.key}`;
          this.scene.add(chunk.root); chunk.job = null;
        }
      }
      if (performance.now() >= deadline) break;
    }
    this.updateActor('train', new THREE.Vector3(-64, 6.8, -80), focus, train, elapsedSeconds);
    this.updateActor('boat', new THREE.Vector3(riverX(42), .4, 42), focus, houseboat, elapsedSeconds);
  }
  updateActor(id, anchor, focus, build, seconds) {
    const distance = Math.hypot(anchor.x - focus.x, anchor.z - focus.z);
    let actor = this.actors.get(id);
    if (!actor && distance <= this.loadRadius) { actor = build(); actor.name = id; this.actors.set(id, actor); this.scene.add(actor); }
    if (!actor) return;
    if (distance > this.unloadRadius) { disposeGroup(actor); this.actors.delete(id); return; }
    if (id === 'train') {
      // Smooth shuttling keeps all four cars on the elevated line.
      actor.position.set(-46 + Math.sin(seconds * .09) * 33, anchor.y, anchor.z);
    } else {
      const z = 44 + Math.sin(seconds * .035) * 28;
      actor.position.set(riverX(z), .4 + Math.sin(seconds * 1.2) * .12, z);
      actor.rotation.y = -Math.PI / 2;
      actor.rotation.z = Math.sin(seconds * .7) * .012;
    }
  }
  get loadingCount() { return [...this.chunks.values()].filter(c => c.job).length; }
  dispose() {
    if (this.disposed) return;
    this.disposed = true;
    for (const chunk of this.chunks.values()) { chunk.job?.return(); if (chunk.root) disposeGroup(chunk.root); }
    this.actors.forEach(disposeGroup); this.actors.clear(); this.chunks.clear();
  }
}
